baseOutputDir:
  /home/blaughli/tracking_project_v2/tracking_to_do_full_nR_20_nS_15
baseInputDirPre:
  /home/blaughli/symbolic_links_ROMS/WC15_hindcast_from_atlantic_202410_compressed
baseYear:
  1995
runDetails:
  -
testSwitch:
  False 
modelConfigDict:
  'drift:vertical_advection': True
  'drift:vertical_mixing': True
  'drift:max_lifespan_days': 150
  'drift:random_velocity_kick': 0.05
  'drift:velocity_kick_depth_max': 800
  'drift:velocity_kick_depth_e_folding_scale': 200
  'general:coastline_action': 'previous'
  'general:use_auto_landmask': False
behaviorList:
  - physicsOnly
romsRunDirectories:
  - single_run
numRunsPerJob:
  20
nSeed:
  15
hisFileNamePre:
  wc15n_
configFileTemplate:
  /home/blaughli/tracking_project_v2/config_files/config_template.config.yaml
dtCalc:
  60
dtSave:
  1440
bufferLength:
  100
seedSpacing:
  2
logLevel:
  20
newVariables:
    'CO2flx': 'CO2flx'
    'CalC': 'CalC'
    'DON': 'DON'
    'NH4': 'NH4'
    'NO3': 'NO3'
    'PON': 'PON'
    'Pzooplankton': 'Pzooplankton'
    'SiOH4': 'SiOH4'
    'TIC': 'TIC'
    'alkalinity': 'alkalinity'
    'diatom': 'diatom'
    'mesozooplankton': 'mesozooplankton'
    'microzooplankton': 'microzooplankton'
    'nanophytoplankton': 'nanophytoplankton'
    'omega': 'omega'
    'opal': 'opal'
    'oxygen': 'oxygen'
    'pCO2': 'pCO2'
    'pH': 'pH'
exportVariables:
  - z 
  - sea_water_temperature 
  - sea_water_salinity 
  - CO2flx
  - CalC 
  - DON 
  - NH4 
  - NO3 
  - PON 
  - Pzooplankton 
  - SiOH4 
  - TIC 
  - alkalinity 
  - diatom 
  - mesozooplankton 
  - microzooplankton 
  - nanophytoplankton 
  - omega 
  - opal 
  - oxygen 
  - pCO2 
  - pH
