#!/bin/bash

# For tests in which I only need the first config file generated by "config_generate.py".

configDir=$1
fileExt="yaml"
configFiles=($configDir/*."$fileExt")
tempDir='z_keep'
mkdir -p $configDir/$tempDir
mv ${configFiles[0]} $tempDir
rm $configDir/*.$fileExt
mv $tempDir/* $configDir
rm -r $tempDir
