#!/bin/bash

# For tests in which I only need the first config file generated by "config_generate.py".

configDir=$1
fileExt="yaml"
configFiles=($configDir/*."$fileExt")
tempDir="$configDir/z_keep"
mkdir -p $tempDir
mv ${configFiles[0]} $tempDir
rm $configDir/*.$fileExt
mv $tempDir/* $configDir
###mv $tempDir/* $configDir
rm -r $tempDir
